package com.blogcode.microservices.student.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * JPA entity representing a student, owned exclusively by this service's
 * {@code student_db} database.
 *
 * <p><strong>Why this class exists:</strong> {@link #enrolledCourseId} is
 * intentionally just a plain {@code Long}, not a JPA {@code @ManyToOne}
 * relationship to a {@code Course} entity. In a microservices architecture
 * a foreign key can never point across a database boundary - course-service
 * owns its own database that student-service cannot even connect to. The
 * "relationship" is resolved at request time over HTTP via
 * {@code CourseClient} instead of at the database level, which is the
 * defining characteristic of this architectural style compared to
 * module 5's monolithic JPA relationships.
 */
@Entity
@Table(name = "students")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Student {

    /** Surrogate primary key generated by the database identity column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Student's given name. */
    @Column(nullable = false, length = 100)
    private String firstName;

    /** Student's family name. */
    @Column(nullable = false, length = 100)
    private String lastName;

    /** Student's contact email address. */
    @Column(nullable = false, unique = true, length = 150)
    private String email;

    /**
     * Id of the course (owned by course-service) this student is enrolled
     * in. May be {@code null} if the student has not enrolled in anything
     * yet. See the class Javadoc for why this is not a JPA relationship.
     */
    @Column
    private Long enrolledCourseId;

    /** Audit timestamp set once when the row is first inserted. */
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /** Audit timestamp updated every time the student is saved. */
    @Column(nullable = false)
    private Instant updatedAt;

    /**
     * Hibernate lifecycle callback invoked automatically before the first
     * INSERT, stamping both audit timestamps.
     */
    @jakarta.persistence.PrePersist
    protected void onCreate() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Hibernate lifecycle callback invoked automatically before every
     * UPDATE, keeping {@code updatedAt} accurate.
     */
    @jakarta.persistence.PreUpdate
    protected void onUpdate() {
        this.updatedAt = Instant.now();
    }
}
