package com.blogcode.studentcrudapi.controller;

import com.blogcode.studentcrudapi.dto.StudentRequest;
import com.blogcode.studentcrudapi.dto.StudentResponse;
import com.blogcode.studentcrudapi.service.StudentService;
import jakarta.validation.Valid;
import java.util.List;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

/**
 * REST controller exposing full CRUD (Create, Read, Update, Delete)
 * operations for student records, plus two read-only search endpoints.
 *
 * <p>Following the same layering established in 01-hello-spring, this
 * controller contains no business logic or persistence code itself - every
 * handler method simply validates/extracts input from the HTTP request and
 * delegates to {@link StudentService}, then returns the result (or lets an
 * exception propagate up to {@code GlobalExceptionHandler}). This keeps the
 * web layer thin and the business logic independently testable.
 */
@Slf4j
@RestController
@RequestMapping("/api/v1/students")
@RequiredArgsConstructor
public class StudentController {

    /**
     * Service layer collaborator injected via the constructor generated by
     * Lombok's {@link RequiredArgsConstructor}, following the
     * constructor-injection pattern used consistently across this
     * curriculum.
     */
    private final StudentService studentService;

    /**
     * Lists every student currently stored.
     *
     * <p>Mapped to {@code GET /api/v1/students}.
     *
     * @return the full list of {@link StudentResponse} DTOs, serialized as
     *         a JSON array with HTTP status {@code 200 OK}.
     */
    @GetMapping
    public List<StudentResponse> getAllStudents() {
        log.info("Handling GET /api/v1/students");
        return studentService.getAllStudents();
    }

    /**
     * Retrieves a single student by their unique identifier.
     *
     * <p>Mapped to {@code GET /api/v1/students/{id}}. If no student exists
     * with the given id, {@link StudentService#getStudentById(Long)} throws
     * a {@code ResourceNotFoundException}, which
     * {@code GlobalExceptionHandler} converts into a {@code 404 Not Found}
     * response - this method itself contains no error-handling code.
     *
     * @param id the identifier extracted from the URL path segment
     *           {@code {id}} via {@link PathVariable}.
     * @return the matching {@link StudentResponse}, with HTTP status
     *         {@code 200 OK}.
     */
    @GetMapping("/{id}")
    public StudentResponse getStudentById(@PathVariable Long id) {
        log.info("Handling GET /api/v1/students/{}", id);
        return studentService.getStudentById(id);
    }

    /**
     * Searches for students whose first or last name contains the given
     * keyword.
     *
     * <p>Mapped to {@code GET /api/v1/students/search?keyword=...}. Uses
     * {@link RequestParam} to bind the mandatory {@code keyword} query
     * string parameter, demonstrating query-parameter-based filtering as an
     * alternative to path variables.
     *
     * @param keyword the case-insensitive substring to search for within
     *                student names.
     * @return every matching {@link StudentResponse}; an empty JSON array
     *         if none match, still with HTTP status {@code 200 OK}.
     */
    @GetMapping("/search")
    public List<StudentResponse> searchStudents(@RequestParam String keyword) {
        log.info("Handling GET /api/v1/students/search?keyword={}", keyword);
        return studentService.searchStudents(keyword);
    }

    /**
     * Retrieves every student enrolled in a given course.
     *
     * <p>Mapped to {@code GET /api/v1/students/course/{course}}, showing a
     * second style of filtering (a path variable this time) compared to
     * {@link #searchStudents(String)}.
     *
     * @param course the exact course/program name extracted from the URL
     *               path segment {@code {course}}.
     * @return every {@link StudentResponse} enrolled in {@code course}; an
     *         empty JSON array if none match.
     */
    @GetMapping("/course/{course}")
    public List<StudentResponse> getStudentsByCourse(@PathVariable String course) {
        log.info("Handling GET /api/v1/students/course/{}", course);
        return studentService.getStudentsByCourse(course);
    }

    /**
     * Creates a new student record.
     *
     * <p>Mapped to {@code POST /api/v1/students}. The {@link Valid}
     * annotation instructs Spring MVC to run Bean Validation against the
     * deserialized {@link StudentRequest} before this method body executes;
     * any constraint violation short-circuits the request straight to
     * {@code GlobalExceptionHandler#handleValidationErrors}, producing a
     * {@code 400 Bad Request} response.
     *
     * @param request the validated request body describing the new
     *                student.
     * @return the newly created {@link StudentResponse}, including its
     *         database-generated id, returned with HTTP status
     *         {@code 201 Created} to signal that a new resource was
     *         created.
     */
    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    public StudentResponse createStudent(@Valid @RequestBody StudentRequest request) {
        log.info("Handling POST /api/v1/students for email='{}'", request.email());
        return studentService.createStudent(request);
    }

    /**
     * Updates an existing student record with new values.
     *
     * <p>Mapped to {@code PUT /api/v1/students/{id}}. Combines a
     * {@link PathVariable} (identifying which student to update) with a
     * validated {@link RequestBody} (containing the new field values) - a
     * common pattern for "full replace" update endpoints.
     *
     * @param id      the identifier of the student to update.
     * @param request the validated request body containing the new values.
     * @return the updated {@link StudentResponse}, with HTTP status
     *         {@code 200 OK}.
     */
    @PutMapping("/{id}")
    public StudentResponse updateStudent(@PathVariable Long id, @Valid @RequestBody StudentRequest request) {
        log.info("Handling PUT /api/v1/students/{}", id);
        return studentService.updateStudent(id, request);
    }

    /**
     * Deletes a student record.
     *
     * <p>Mapped to {@code DELETE /api/v1/students/{id}}. Returns HTTP
     * status {@code 204 No Content} - the conventional response for a
     * successful deletion where there is no meaningful body to return.
     *
     * @param id the identifier of the student to delete.
     */
    @DeleteMapping("/{id}")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    public void deleteStudent(@PathVariable Long id) {
        log.info("Handling DELETE /api/v1/students/{}", id);
        studentService.deleteStudent(id);
    }
}
