spring.application.name=schoolsystem

spring.datasource.url=jdbc:postgresql://localhost:5432/schoolsystem
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
