package com.blogcode.studentcrudapi.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * JPA entity mapping a single row of the {@code student} table.
 *
 * <p>Unlike the {@code Greeting} record used in the 01-hello-spring project,
 * this class is a mutable, framework-managed object: JPA/Hibernate needs to
 * be able to construct instances reflectively (hence the required
 * no-args constructor) and to set field values after the object is loaded
 * from the database (hence the setters). This is precisely why entities are
 * modelled as classes rather than records - records are immutable and
 * final, which is incompatible with how JPA proxies and lazily populates
 * managed entities.
 *
 * <p>Lombok annotations remove the boilerplate that would otherwise be
 * required:
 * <ul>
 *   <li>{@link Getter} / {@link Setter} - generate accessor and mutator
 *       methods for every field.</li>
 *   <li>{@link NoArgsConstructor} - required by the JPA specification so
 *       the persistence provider can instantiate entities via reflection.</li>
 *   <li>{@link AllArgsConstructor} - convenient for tests and for the
 *       {@link Builder} below.</li>
 *   <li>{@link Builder} - provides a fluent, readable way to construct fully
 *       populated {@code Student} instances (e.g. in the mapper and in
 *       tests) without a long constructor argument list.</li>
 *   <li>{@link ToString} - useful for logging; note it deliberately doesn't
 *       need to be excluded here since {@code Student} has no relationships
 *       to other entities that could cause infinite recursion.</li>
 * </ul>
 */
@Entity
@Table(name = "student")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
public class Student {

    /**
     * Surrogate primary key, generated by the database itself.
     *
     * <p>{@link GenerationType#IDENTITY} delegates id generation to an
     * auto-increment column, which H2 (and most relational databases)
     * support natively - a simple, predictable strategy well suited to a
     * teaching project.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The student's first name. Mapped as {@code NOT NULL} because every
     * student record must identify who it belongs to.
     */
    @Column(nullable = false)
    private String firstName;

    /**
     * The student's last name.
     */
    @Column(nullable = false)
    private String lastName;

    /**
     * The student's email address. Marked {@code unique = true} so the
     * database itself enforces that no two students share an email,
     * complementing the application-level {@code @Email} validation applied
     * to incoming request DTOs.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * The name of the course/program the student is currently enrolled in,
     * e.g. {@code "Computer Science"}. Used by the
     * {@code GET /api/v1/students/course/{course}} endpoint to filter
     * students.
     */
    @Column(nullable = false)
    private String course;

    /**
     * The student's age in years at the time the record was created or last
     * updated.
     */
    @Column(nullable = false)
    private Integer age;
}
