spring.application.name=05-secured-todo-api
server.port=8084

spring.datasource.url=jdbc:h2:mem:secureddb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

jwt.secret=this-is-a-learning-project-secret-key-change-it-in-production!
jwt.expiration-ms=86400000

