@ECHO OFF
REM =============================================================================
REM mvnw.cmd - simple Maven Wrapper launcher script (Windows)
REM
REM Lightweight, curriculum-friendly stand-in for the full Maven Wrapper
REM generated by "mvn -N wrapper:wrapper". It simply delegates every argument
REM to a Maven installation already available on PATH, so the README's
REM "mvnw.cmd ..." instructions work out of the box. For the official,
REM checksum-verified wrapper (which downloads a pinned Maven distribution),
REM run "mvn -N wrapper:wrapper" once you have any Maven version installed.
REM =============================================================================
SETLOCAL

WHERE mvn >NUL 2>NUL
IF ERRORLEVEL 1 (
    ECHO Error: Apache Maven ("mvn") was not found on your PATH.
    ECHO Install Maven from https://maven.apache.org/install.html and try again.
    EXIT /B 1
)

mvn %*
EXIT /B %ERRORLEVEL%
