package com.blogcode.ecommerce.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * JPA entity representing a product category (e.g. "Electronics", "Books").
 *
 * <p><strong>Why this class exists:</strong> categories model a classic
 * many-to-many relationship - a single product can belong to several
 * categories ("Laptop" could be both "Electronics" and "Office Supplies")
 * and a category groups many products. This is one of the trickiest JPA
 * relationship types for beginners because, unlike a one-to-many, there is
 * no natural "owning" foreign key column; instead a join table is required.
 *
 * <p><strong>Lombok note:</strong> we deliberately avoid {@code @Data} on
 * JPA entities. {@code @Data} generates {@code equals()}/{@code hashCode()}
 * from every field, including the {@code products} collection, which would
 * trigger expensive (and sometimes infinite, since {@link Product} points
 * back here) lazy-loading recursion. Instead we hand-write identity-based
 * equality and exclude collections from {@code toString()}.
 */
@Entity
@Table(name = "categories")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = "products")
public class Category {

    /** Surrogate primary key generated by the database identity column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Human-readable, unique category name shown in the storefront UI. */
    @Column(nullable = false, unique = true, length = 100)
    private String name;

    /** Short marketing description of what belongs in this category. */
    @Column(length = 500)
    private String description;

    /**
     * The inverse side of the {@code Product.categories} many-to-many
     * relationship. {@code mappedBy} tells Hibernate that {@link Product}
     * owns the join table ({@code product_category}), so this collection is
     * read-only from Hibernate's point of view unless the owning side is
     * also updated. Initialized eagerly to an empty set to avoid
     * {@code NullPointerException} when building a new category.
     */
    @ManyToMany(mappedBy = "categories")
    @Builder.Default
    private Set<Product> products = new HashSet<>();

    /**
     * Entities use identity/business-key equality (the database id) rather
     * than Lombok's field-based equality, which is the recommended JPA
     * pattern: two managed entities with the same id represent the same row,
     * even if some lazy fields have not been loaded yet.
     *
     * @param o the other object to compare against
     * @return true if {@code o} is a {@link Category} with the same id
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Category category)) {
            return false;
        }
        return id != null && id.equals(category.id);
    }

    /**
     * Matches {@link #equals(Object)} by hashing on the class only when the
     * id is not yet assigned (a transient, unsaved entity), and on the id
     * once persisted. This keeps the hash code stable across the entity's
     * lifecycle, which is required by the {@code Set} contract used above.
     *
     * @return a stable hash code for this entity
     */
    @Override
    public int hashCode() {
        return Objects.hash(getClass());
    }
}
