package com.blogcode.ecommerce.domain;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * JPA entity representing a customer order: the "one" side of a one-to-many
 * relationship with {@link OrderItem}.
 *
 * <p><strong>Why this class exists:</strong> orders demonstrate a classic
 * parent/child aggregate. Order items only make sense in the context of an
 * order, so we make {@link Order} the aggregate root: it owns the lifecycle
 * of its items via {@code cascade = CascadeType.ALL} and
 * {@code orphanRemoval = true}. That means saving an {@code Order} also
 * saves its {@code OrderItem}s, and removing an item from the in-memory
 * list deletes the corresponding row - students never need to call the
 * {@code OrderItemRepository} directly.
 */
@Entity
@Table(name = "orders")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = "items")
public class Order {

    /** Surrogate primary key generated by the database identity column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Simple denormalized identifier for the customer who placed the order.
     * A production system would model a full {@code Customer} entity and a
     * many-to-one relationship here; this curriculum keeps it as a plain
     * field to stay focused on the Product/Category/Order teaching goals.
     */
    @Column(nullable = false, length = 100)
    private String customerEmail;

    /** Current lifecycle state of the order; see {@link OrderStatus}. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private OrderStatus status;

    /**
     * Denormalized order total, recomputed from the line items every time
     * the order is created or modified. Storing it avoids recalculating a
     * SUM on every read, at the cost of needing to keep it consistent -
     * {@link #recalculateTotal()} centralizes that responsibility.
     */
    @Column(nullable = false, precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal totalAmount = BigDecimal.ZERO;

    /** Audit timestamp set once when the order is first inserted. */
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /** Audit timestamp updated every time the order is saved. */
    @Column(nullable = false)
    private Instant updatedAt;

    /**
     * The line items that make up this order. {@code mappedBy} marks this
     * as the inverse side; {@link OrderItem#getOrder()} owns the foreign
     * key. {@code CascadeType.ALL} + {@code orphanRemoval = true} means the
     * {@link Order} aggregate fully controls the lifecycle of its items.
     */
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<OrderItem> items = new ArrayList<>();

    /**
     * Adds a line item to the order and keeps both sides of the
     * bidirectional relationship in sync, the same pattern used by
     * {@link Product#addCategory(Category)}.
     *
     * @param item the order item to attach to this order
     */
    public void addItem(OrderItem item) {
        items.add(item);
        item.setOrder(this);
    }

    /**
     * Recomputes {@link #totalAmount} by summing {@code unitPrice * quantity}
     * across every line item. Called by the service layer whenever items
     * are added or removed so the denormalized total never drifts out of
     * sync with the source-of-truth line items.
     */
    public void recalculateTotal() {
        this.totalAmount = items.stream()
                .map(item -> item.getUnitPrice().multiply(BigDecimal.valueOf(item.getQuantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }

    /**
     * Hibernate lifecycle callback invoked automatically before the first
     * INSERT, stamping both audit timestamps.
     */
    @jakarta.persistence.PrePersist
    protected void onCreate() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
        if (this.status == null) {
            this.status = OrderStatus.PENDING;
        }
    }

    /**
     * Hibernate lifecycle callback invoked automatically before every
     * UPDATE, keeping {@code updatedAt} accurate.
     */
    @jakarta.persistence.PreUpdate
    protected void onUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Entities use identity/business-key equality rather than Lombok's
     * field-based equality; see {@link Category#equals(Object)} for the
     * detailed rationale.
     *
     * @param o the other object to compare against
     * @return true if {@code o} is an {@link Order} with the same id
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Order order)) {
            return false;
        }
        return id != null && id.equals(order.id);
    }

    /**
     * @return a stable hash code, consistent with {@link #equals(Object)}
     */
    @Override
    public int hashCode() {
        return Objects.hash(getClass());
    }
}
