package com.blogcode.ecommerce.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.util.Objects;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * JPA entity representing a single line item within an {@link Order}.
 *
 * <p><strong>Why this class exists:</strong> this is the "many" side of two
 * different relationships at once - many-to-one back to {@link Order} (the
 * aggregate that owns this row) and many-to-one to {@link Product} (the
 * catalog item being purchased). We snapshot {@code unitPrice} at the time
 * of purchase rather than always reading {@code Product.price} live,
 * because historical orders must keep showing the price the customer
 * actually paid even if the product's price changes later.
 */
@Entity
@Table(name = "order_items")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = {"order", "product"})
public class OrderItem {

    /** Surrogate primary key generated by the database identity column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Owning side of the one-to-many relationship with {@link Order}.
     * {@code FetchType.LAZY} avoids pulling the parent order (and
     * transitively every sibling item) every time a single item is loaded.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false)
    private Order order;

    /**
     * The product being purchased. Also {@code LAZY} so listing order items
     * does not force-load full product/category graphs unless requested.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /** How many units of {@link #product} were purchased. */
    @Column(nullable = false)
    private Integer quantity;

    /**
     * Snapshot of {@code Product.price} at the moment the order was placed;
     * see the class-level Javadoc for why this must not simply reference
     * the live product price.
     */
    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal unitPrice;

    /**
     * Computes the line subtotal ({@code unitPrice * quantity}) on demand,
     * kept as a derived value rather than a persisted column since it is
     * cheap to compute and would otherwise need to stay in sync manually.
     *
     * @return the subtotal for this line item
     */
    public BigDecimal getSubtotal() {
        return unitPrice.multiply(BigDecimal.valueOf(quantity));
    }

    /**
     * Entities use identity/business-key equality rather than Lombok's
     * field-based equality; see {@link Category#equals(Object)} for the
     * detailed rationale.
     *
     * @param o the other object to compare against
     * @return true if {@code o} is an {@link OrderItem} with the same id
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof OrderItem orderItem)) {
            return false;
        }
        return id != null && id.equals(orderItem.id);
    }

    /**
     * @return a stable hash code, consistent with {@link #equals(Object)}
     */
    @Override
    public int hashCode() {
        return Objects.hash(getClass());
    }
}
