package com.blogcode.ecommerce.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * JPA entity representing a sellable product in the catalog.
 *
 * <p><strong>Why this class exists:</strong> {@code Product} is the "owning"
 * side of the many-to-many relationship with {@link Category}. Owning side
 * means this entity's mapping declares the {@code @JoinTable}, so Hibernate
 * uses it to decide how to insert/delete rows in the {@code product_category}
 * join table whenever the {@code categories} collection changes.
 *
 * <p>This entity is also the "one" side of the one-to-many relationship with
 * {@link OrderItem}: a product can appear in many order line items over
 * time, but each {@link OrderItem} snapshot references exactly one product.
 */
@Entity
@Table(name = "products")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = {"categories"})
public class Product {

    /** Surrogate primary key generated by the database identity column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Product title shown to shoppers, e.g. "Mechanical Keyboard". */
    @Column(nullable = false, length = 200)
    private String name;

    /** Longer free-text description rendered on the product detail page. */
    @Column(length = 2000)
    private String description;

    /**
     * Unit price using {@link BigDecimal} rather than {@code double}. Money
     * must never use floating point types because binary floating point
     * cannot represent all decimal fractions exactly, which silently
     * corrupts totals - a critical lesson for any e-commerce system.
     */
    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal price;

    /** Number of units currently available to sell. */
    @Column(nullable = false)
    @Builder.Default
    private Integer stockQuantity = 0;

    /**
     * Public URL of the product's image, populated after a client calls the
     * image upload endpoint ({@code POST /api/v1/uploads/images}) and then
     * PATCHes/PUTs the product with the returned URL.
     */
    @Column(length = 500)
    private String imageUrl;

    /** Audit timestamp set once when the row is first inserted. */
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /** Audit timestamp updated every time the product is saved. */
    @Column(nullable = false)
    private Instant updatedAt;

    /**
     * The owning side of the many-to-many relationship with {@link Category}.
     * {@code @JoinTable} explicitly names the join table and both foreign
     * key columns so the schema is easy to read directly in PostgreSQL.
     * {@code FetchType} defaults to LAZY for {@code @ManyToMany}, which is
     * intentional: we do not want every product list query to also join
     * every category unless the caller actually needs them.
     */
    @ManyToMany
    @JoinTable(
            name = "product_category",
            joinColumns = @JoinColumn(name = "product_id"),
            inverseJoinColumns = @JoinColumn(name = "category_id"))
    @Builder.Default
    private Set<Category> categories = new HashSet<>();

    /**
     * Hibernate lifecycle callback invoked automatically before the very
     * first INSERT. Centralizing timestamp logic here means no service
     * method can forget to stamp {@code createdAt}/{@code updatedAt}.
     */
    @jakarta.persistence.PrePersist
    protected void onCreate() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Hibernate lifecycle callback invoked automatically before every
     * UPDATE, keeping {@code updatedAt} accurate without service code
     * having to remember to set it manually.
     */
    @jakarta.persistence.PreUpdate
    protected void onUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Convenience method that keeps both sides of the many-to-many
     * relationship in sync in a single call, avoiding a common beginner bug
     * where only one side of a bidirectional association is updated.
     *
     * @param category the category to associate with this product
     */
    public void addCategory(Category category) {
        this.categories.add(category);
        category.getProducts().add(this);
    }

    /**
     * Convenience method that removes this product from a category on both
     * sides of the relationship, mirroring {@link #addCategory(Category)}.
     *
     * @param category the category to disassociate from this product
     */
    public void removeCategory(Category category) {
        this.categories.remove(category);
        category.getProducts().remove(this);
    }

    /**
     * Entities use identity/business-key equality rather than Lombok's
     * field-based equality; see {@link Category#equals(Object)} for the
     * detailed rationale.
     *
     * @param o the other object to compare against
     * @return true if {@code o} is a {@link Product} with the same id
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Product product)) {
            return false;
        }
        return id != null && id.equals(product.id);
    }

    /**
     * @return a stable hash code, consistent with {@link #equals(Object)}
     */
    @Override
    public int hashCode() {
        return Objects.hash(getClass());
    }
}
