package com.blogcode.hellospring.controller;

import com.blogcode.hellospring.model.Greeting;
import com.blogcode.hellospring.service.GreetingService;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

/**
 * REST controller exposing the greeting endpoints of this curriculum
 * project.
 *
 * <p>{@link RestController} is a convenience annotation combining
 * {@code @Controller} (marks the class as a Spring MVC controller bean) and
 * {@code @ResponseBody} (tells Spring MVC to serialize every method's return
 * value directly into the HTTP response body - as JSON, via Jackson - instead
 * of resolving it to a view/template name). This is the standard shape of a
 * "data API" controller as opposed to a server-rendered web page controller.
 *
 * <p>{@link RequestMapping} at the class level defines a common URL prefix
 * ({@code /api/v1/greetings}) shared by every handler method below, keeping
 * the mapping annotations on individual methods short and focused on the
 * remainder of the path.
 */
@Slf4j
@RestController
@RequestMapping("/api/v1/greetings")
@RequiredArgsConstructor
public class GreetingController {

    /**
     * The service layer collaborator used to build {@link Greeting}
     * instances.
     *
     * <p>Declared as {@code final} and injected through the constructor
     * generated by Lombok's {@link RequiredArgsConstructor} annotation
     * (placed on the class). Lombok inspects every {@code final} field
     * without a default value and generates a constructor that accepts
     * exactly those fields as parameters. Spring then automatically calls
     * that generated constructor and supplies the single
     * {@code GreetingService} bean registered in the application context -
     * this is "constructor injection", the pattern recommended by the
     * Spring team because it makes dependencies explicit, supports
     * immutability, and allows the class to be instantiated in plain unit
     * tests without needing a full Spring context.
     */
    private final GreetingService greetingService;

    /**
     * Returns the default "Hello, World!" greeting.
     *
     * <p>Mapped to {@code GET /api/v1/greetings}. This is intentionally the
     * simplest possible endpoint - no path variables, no request body, no
     * validation - so beginners can verify their setup works before moving
     * on to the parameterised endpoint below.
     *
     * @return a {@link Greeting} which Spring MVC serializes to a JSON
     *         response body with HTTP status {@code 200 OK}.
     */
    @GetMapping
    public Greeting getDefaultGreeting() {
        log.info("Handling GET /api/v1/greetings");
        return greetingService.createDefaultGreeting();
    }

    /**
     * Creates a personalised greeting for the name supplied in the request
     * body.
     *
     * <p>Mapped to {@code POST /api/v1/greetings}. Demonstrates reading and
     * validating a JSON request body:
     * <ul>
     *   <li>{@link RequestBody} instructs Spring MVC to deserialize the
     *       incoming JSON payload into a {@link GreetingRequest} instance
     *       using Jackson.</li>
     *   <li>{@code @Valid} on the parameter tells Spring MVC to run Bean
     *       Validation against the deserialized object <em>before</em> this
     *       method body executes, checking the {@code @NotBlank} constraint
     *       declared on {@link GreetingRequest#name()}. If validation fails,
     *       Spring MVC short-circuits the request with a
     *       {@code 400 Bad Request} response. A much richer example of
     *       validation-driven error handling is explored in the
     *       02-student-crud-api project.</li>
     * </ul>
     *
     * @param request the deserialized request body containing the name to
     *                greet.
     * @return a {@link Greeting} personalised for {@link GreetingRequest#name()},
     *         returned with HTTP status {@code 201 Created} because a new
     *         greeting resource conceptually came into existence.
     */
    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    public Greeting createGreeting(@Valid @RequestBody GreetingRequest request) {
        log.info("Handling POST /api/v1/greetings for name='{}'", request.name());
        return greetingService.createGreetingFor(request.name());
    }

    /**
     * Request payload accepted by {@link #createGreeting(GreetingRequest)}.
     *
     * <p>Declared as a small, private-to-the-controller {@code record}
     * nested inside {@code GreetingController} rather than as a top-level
     * class. This is a deliberate teaching choice: because
     * {@code GreetingRequest} is only ever used as the input shape for this
     * one endpoint, nesting it keeps the "public API surface" of the
     * controller self-contained and easy to read in a single file, while
     * still demonstrating the DTO (Data Transfer Object) pattern - a type
     * dedicated purely to carrying data across the web boundary, kept
     * separate from the internal {@link Greeting} domain record.
     *
     * @param name the recipient's name; annotated with {@link NotBlank}
     *             (from {@code jakarta.validation.constraints}) to document
     *             the constraint that it must not be {@code null}, empty, or
     *             whitespace-only.
     */
    public record GreetingRequest(@NotBlank String name) {
    }
}
