package com.blogcode.microservices.course.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * JPA entity representing a course offered by the institution.
 *
 * <p><strong>Why this class exists:</strong> this entity is intentionally
 * simple compared to the module 5 e-commerce domain - the teaching focus of
 * this curriculum module is the *microservices plumbing* (discovery,
 * routing, inter-service calls) rather than advanced JPA modeling. Even so,
 * it demonstrates the same "own database, plain entity" pattern every
 * service in this system follows: {@code course-service} is the only
 * service permitted to read or write the {@code courses} table directly.
 */
@Entity
@Table(name = "courses")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Course {

    /** Surrogate primary key generated by the database identity column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Course title, e.g. "Introduction to Databases". */
    @Column(nullable = false, length = 200)
    private String title;

    /** Longer free-text description of the course content. */
    @Column(length = 2000)
    private String description;

    /** Name of the instructor teaching the course. */
    @Column(nullable = false, length = 120)
    private String instructor;

    /** Number of academic credits the course is worth. */
    @Column(nullable = false)
    private Integer credits;

    /** Audit timestamp set once when the row is first inserted. */
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /** Audit timestamp updated every time the course is saved. */
    @Column(nullable = false)
    private Instant updatedAt;

    /**
     * Hibernate lifecycle callback invoked automatically before the first
     * INSERT, stamping both audit timestamps.
     */
    @jakarta.persistence.PrePersist
    protected void onCreate() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Hibernate lifecycle callback invoked automatically before every
     * UPDATE, keeping {@code updatedAt} accurate.
     */
    @jakarta.persistence.PreUpdate
    protected void onUpdate() {
        this.updatedAt = Instant.now();
    }
}
