package com.blogcode.blogapi.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.time.Instant;

/**
 * JPA entity representing a single comment left on a {@link Post}.
 *
 * <p>This class is the "many" side of the Post &lt;-&gt; Comment relationship, and the
 * <b>owning</b> side of the association: it declares the {@code @ManyToOne} field and the
 * physical {@code post_id} foreign key column. In JPA, the owning side is always the side
 * that holds the {@code @JoinColumn} - this is what the {@code mappedBy} attribute on
 * {@link Post#getComments()} refers back to.
 */
@Entity
@Table(name = "comments")
@Getter
@Setter
@NoArgsConstructor // required by JPA for entity instantiation via reflection.
@AllArgsConstructor
@Builder
@ToString(exclude = "post") // avoid recursive toString() calls between Comment and Post.
public class Comment {

    /** Surrogate primary key, generated by the database identity/sequence strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Free-text name of whoever left the comment. */
    @Column(nullable = false, length = 100)
    private String author;

    /** The comment's text body. */
    @Column(nullable = false, length = 2000)
    private String content;

    /**
     * The post this comment belongs to.
     *
     * <p>{@code fetch = FetchType.LAZY} is used deliberately: when we load a list of
     * comments we almost never need the full parent post loaded eagerly too, so lazy
     * loading avoids unnecessary joins/queries and the classic N+1 pitfall in reverse.
     * {@code @JoinColumn(name = "post_id")} defines the actual foreign key column on the
     * {@code comments} table.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "post_id", nullable = false)
    private Post post;

    /** Timestamp set once, the first time this row is persisted. */
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * JPA lifecycle callback that stamps {@code createdAt} automatically on insert so the
     * service layer never has to remember to set it manually.
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = Instant.now();
    }
}
