package com.blogcode.blogapi.entity;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OrderBy;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * JPA entity representing a single blog post.
 *
 * <p>This class is the "one" side of a One-To-Many relationship with {@link Comment}: a
 * single post can have many comments, but every comment belongs to exactly one post. The
 * relationship is modelled as <b>bidirectional</b> so that students can see both directions
 * of a JPA association in one project:
 * <ul>
 *     <li>{@code Post.comments} (the "inverse"/non-owning side, marked with {@code mappedBy})</li>
 *     <li>{@code Comment.post} (the "owning" side, which actually holds the foreign key column)</li>
 * </ul>
 *
 * <p>Lombok's {@code @Getter}/{@code @Setter} annotations remove the need to hand-write
 * accessor boilerplate, which lets the class stay focused on the JPA mapping itself -
 * exactly the kind of code a beginner should be reading first.
 */
@Entity
@Table(name = "posts")
@Getter
@Setter
@NoArgsConstructor // required by JPA: Hibernate instantiates entities via a no-args constructor.
@AllArgsConstructor
@Builder
@ToString(exclude = "comments") // avoid recursive toString() calls between Post and Comment.
public class Post {

    /** Surrogate primary key, generated by the database identity/sequence strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Short human-readable title of the post. Required and length-limited at the DB level. */
    @Column(nullable = false, length = 200)
    private String title;

    /** Full body of the post. Stored as a large object since post content can be long. */
    @Lob
    @Column(nullable = false)
    private String content;

    /**
     * Free-text author name. A real production system would replace this with a foreign
     * key to a User entity (see project 4, {@code secure-notes-api}, for that pattern),
     * but a plain string keeps this first JPA-relationship project focused and simple.
     */
    @Column(nullable = false, length = 100)
    private String author;

    /**
     * The child comments belonging to this post.
     *
     * <p>{@code mappedBy = "post"} tells Hibernate that the {@link Comment#getPost()} field
     * owns the relationship (i.e. the {@code comments.post_id} foreign key column lives on
     * the comment table), so {@code Post} does not need - and must not declare - a join
     * column of its own.
     *
     * <p>{@code cascade = CascadeType.ALL} plus {@code orphanRemoval = true} means that
     * saving or deleting a {@code Post} automatically saves/deletes its comments, and
     * removing a comment from this list deletes it from the database - a very common
     * "aggregate root" pattern for parent/child entities that never make sense on their own.
     */
    @OneToMany(mappedBy = "post", cascade = CascadeType.ALL, orphanRemoval = true, fetch = jakarta.persistence.FetchType.LAZY)
    @OrderBy("createdAt ASC")
    @Builder.Default
    private List<Comment> comments = new ArrayList<>();

    /** Timestamp set once, the first time this row is persisted. Never updated afterwards. */
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp refreshed every time this row is updated. */
    @Column(nullable = false)
    private Instant updatedAt;

    /**
     * JPA lifecycle callback invoked automatically right before the entity is first
     * inserted. Using {@code @PrePersist} (instead of setting the timestamp manually in
     * every service method) guarantees every post gets consistent, server-side timestamps
     * no matter which code path creates it.
     */
    @PrePersist
    protected void onCreate() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * JPA lifecycle callback invoked automatically right before an existing row is
     * updated, keeping {@code updatedAt} accurate without repeating that logic in the
     * service layer.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Convenience helper that keeps both sides of the bidirectional association in sync.
     * Whenever a comment is added to a post, this method also points the comment back at
     * this post, preventing the classic JPA bug where only one side of a relationship is
     * updated in memory.
     *
     * @param comment the comment to attach to this post
     */
    public void addComment(Comment comment) {
        comments.add(comment);
        comment.setPost(this);
    }

    /**
     * Convenience helper that removes a comment from this post while also clearing the
     * back-reference, working together with {@code orphanRemoval = true} to delete the
     * comment row from the database.
     *
     * @param comment the comment to detach from this post
     */
    public void removeComment(Comment comment) {
        comments.remove(comment);
        comment.setPost(null);
    }
}
