package com.blogcode.studentcrudapi.service.impl;

import com.blogcode.studentcrudapi.dto.StudentRequest;
import com.blogcode.studentcrudapi.dto.StudentResponse;
import com.blogcode.studentcrudapi.entity.Student;
import com.blogcode.studentcrudapi.exception.ResourceNotFoundException;
import com.blogcode.studentcrudapi.mapper.StudentMapper;
import com.blogcode.studentcrudapi.repository.StudentRepository;
import com.blogcode.studentcrudapi.service.StudentService;
import java.util.List;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Default implementation of {@link StudentService}, containing all business
 * logic for managing student records.
 *
 * <p>Annotated with {@link Service} so Spring's component scanning
 * discovers and registers it as a singleton bean, injectable anywhere a
 * {@link StudentService} dependency is declared - most notably in
 * {@code StudentController}, wired together via constructor injection.
 *
 * <p>The class-level {@link Transactional} annotation (marked
 * {@code readOnly = true}) applies to every method by default, signalling
 * to Spring's transaction infrastructure that these operations only read
 * data - allowing some persistence providers/drivers to apply read-only
 * optimisations (e.g. skipping dirty-checking flushes). The handful of
 * methods that actually mutate data override this default with their own
 * {@code @Transactional} (read-write) annotation, following the principle
 * of "read-only by default, opt in to writes" which keeps performance
 * optimisations automatic while remaining safe.
 */
@Slf4j
@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class StudentServiceImpl implements StudentService {

    /**
     * The Spring Data JPA repository used to load and persist
     * {@link Student} entities. Injected via the constructor generated by
     * Lombok's {@link RequiredArgsConstructor}, following the same
     * constructor-injection pattern used throughout this curriculum.
     */
    private final StudentRepository studentRepository;

    /**
     * {@inheritDoc}
     *
     * <p>Inherits the class-level read-only transaction: since Spring Data
     * JPA already wraps repository calls in a transaction, this annotation
     * mainly documents intent and enables the read-only optimisation
     * mentioned above.
     */
    @Override
    public List<StudentResponse> getAllStudents() {
        log.debug("Fetching all students");
        return studentRepository.findAll().stream()
                .map(StudentMapper::toResponse)
                .toList();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentResponse getStudentById(Long id) {
        log.debug("Fetching student with id={}", id);
        Student student = findStudentOrThrow(id);
        return StudentMapper.toResponse(student);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<StudentResponse> searchStudents(String keyword) {
        log.debug("Searching students with keyword='{}'", keyword);
        return studentRepository.searchByKeyword(keyword).stream()
                .map(StudentMapper::toResponse)
                .toList();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<StudentResponse> getStudentsByCourse(String course) {
        log.debug("Fetching students enrolled in course='{}'", course);
        return studentRepository.findByCourse(course).stream()
                .map(StudentMapper::toResponse)
                .toList();
    }

    /**
     * {@inheritDoc}
     *
     * <p>Overrides the class-level read-only default with a read-write
     * transaction, since this method persists a new row. Wrapping the save
     * in a transaction ensures that if anything fails partway through (in a
     * more elaborate implementation that, say, also wrote to a second
     * table), the whole operation would roll back atomically rather than
     * leaving inconsistent data behind.
     */
    @Override
    @Transactional
    public StudentResponse createStudent(StudentRequest request) {
        log.info("Creating student with email='{}'", request.email());
        Student student = StudentMapper.toEntity(request);
        Student saved = studentRepository.save(student);
        return StudentMapper.toResponse(saved);
    }

    /**
     * {@inheritDoc}
     *
     * <p>Loads the managed entity first so {@link StudentMapper#updateEntity}
     * can mutate it in place; because this method runs inside a read-write
     * transaction, Hibernate's dirty-checking automatically issues the
     * necessary {@code UPDATE} statement when the transaction commits, even
     * though {@code save} is still called explicitly below for clarity and
     * to obtain the (in this case unchanged) persisted state back.
     */
    @Override
    @Transactional
    public StudentResponse updateStudent(Long id, StudentRequest request) {
        log.info("Updating student with id={}", id);
        Student existing = findStudentOrThrow(id);
        StudentMapper.updateEntity(existing, request);
        Student saved = studentRepository.save(existing);
        return StudentMapper.toResponse(saved);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @Transactional
    public void deleteStudent(Long id) {
        log.info("Deleting student with id={}", id);
        Student existing = findStudentOrThrow(id);
        studentRepository.delete(existing);
    }

    /**
     * Shared helper that loads a {@link Student} by id or throws a
     * {@link ResourceNotFoundException} if no such student exists.
     *
     * <p>Extracting this lookup-or-throw logic into a single private method
     * avoids repeating the same {@code findById(...).orElseThrow(...)}
     * pattern in every public method above that needs to operate on an
     * existing student.
     *
     * @param id the identifier to look up.
     * @return the matching {@link Student} entity.
     * @throws ResourceNotFoundException if no student exists with the given
     *                                   {@code id}.
     */
    private Student findStudentOrThrow(Long id) {
        return studentRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Student not found with id: " + id));
    }
}
